modLoader = "javafml"
loaderVersion = "[35,)"
license = "MIT"
issueTrackerURL = "https://github.com/Yamahari/tagyoureit/issues"
[[mods]]
modId = "tagyoureit"
version = "1.0.0.0"
displayName = "Tag, You're It!"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tag-youre-it"
logoFile = "logo.png"
credits = "Yamahari and the people of Forge"
authors = "Yamahari"
description = '''
Adds additional functionality to name tags. While holding a nametag in your off/main hand your player name tag
(the one above your head) changes to the display name of the item tag you're holding.
'''

[[dependencies.tagyoureit]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tagyoureit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,1.17)"
ordering = "NONE"
side = "BOTH"
